FROM ubuntu:22.04

WORKDIR /usr/src/ubuntu_docker

RUN apt-get update; apt-get upgrade -y

RUN apt-get install -y build-essential

RUN apt-get install -y python3

RUN apt-get install -y python3-pip

# RUN apt-get install -y python3-dev

# RUN apt-get install -y python3-setuptools

RUN apt-get install -y git

RUN apt-get install -y make